import type { Metadata } from "next";
import { Great_Vibes, Montserrat } from "next/font/google";

import "./globals.css";
import Footer from "@/components/footer";

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  weight: "400", // Great Vibes só tem peso 400
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // escolhe os que for usar
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="theme-peach">
      <body
        className={`${greatVibes.variable} ${montserrat.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <div className="flex-1">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
